version: 0.2

env:
  variables:
    VITE_API_URL: "http://13.40.131.226/api"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install --prefix frontend

  build:
    commands:
      - npm run build --prefix frontend

  post_build:
    commands:
      - echo "Frontend build complete"

artifacts:
  base-directory: frontend
  files:
    - appspec.yml
    - scripts/**/*
    - dist/**/*
  discard-paths: no
