version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing frontend dependencies"
      - cd frontend && npm install

  pre_build:
    commands:
      - echo "Running linter"
      - cd frontend && npm run lint

  build:
    commands:
      - echo "Building React frontend for production"
      - cd frontend && npm run build

  post_build:
    commands:
      - echo "Frontend build complete"

artifacts:
  base-directory: frontend
  files:
    - appspec.yml
    - scripts/**/*
    - dist/**/*
  discard-paths: no
