version: 0.2

env:
  variables:
    APP_DIR: "frontend"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing frontend dependencies"
      - cd $APP_DIR && npm install

  pre_build:
    commands:
      - echo "Running linter"
      - cd $APP_DIR && npm run lint

  build:
    commands:
      - echo "Building React frontend for production"
      - cd $APP_DIR && npm run build

  post_build:
    commands:
      - echo "Frontend build complete"

artifacts:
  base-directory: frontend
  files:
    - appspec.yml
    - scripts/**/*
    - dist/**/*
  discard-paths: no
