version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install --prefix backend

  build:
    commands:
      - echo "Backend build complete"

  post_build:
    commands:
      - echo "Backend packaging complete"

artifacts:
  base-directory: backend
  files:
    - appspec.yml
    - scripts/**/*
    - app.js
    - server.js
    - package.json
    - package-lock.json
    - db.sql
    - configs/**/*
    - controllers/**/*
    - routes/**/*
  discard-paths: no
